name: CI Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: latest
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
  build:
    name: Build ${{ matrix.node-version }} @ ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 20
          - 22
          - latest
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
